- name: install brew packages
  homebrew:
    name: "{{ packages.brew }}"
    state: latest
    update_homebrew: yes

  #- name: download raw packages
  #  get_url:
  #    url: "{{ item.url }}"
  #    dest: "{{ item.dest }}"
  #    mode: 0755
  #  loop: "{{ packages.raw }}"

- name: make sure directories exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/fish"

- name: copy fish files
  copy:
    src: config.fish
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"

- name: change shell to fish
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish

- name: use .gitconfig
  copy:
    src: gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"

- name: use ssh config
  copy:
    src: ssh.config
    dest: "{{ ansible_user_dir }}/.ssh/config"
