---

- name: install groups
  yum:
    name: "@{{ item }}"
    state: latest
  loop: "{{ packages.groups }}"

- name: install common packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.packages }}"

- name: download raw packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop: "{{ packages.raw }}"

- name: copy tmux files
  become: "{{ ansible_user_id }}"
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"

- name: copy fish files
  become: "{{ ansible_user_id }}"
  copy:
    src: config.fish
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"

- name: change shell to fish
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish

- name: use .gitconfig
  become: "{{ ansible_user_id }}"
  copy:
    src: gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"
