---

- name: create the gdm profile
  copy:
    content: |
      user-db:user
      system-db:gdm
      file-db:/usr/share/gdm/greeter-dconf-defaults
    dest: /etc/dconf/profile/gdm
  tags: ["gnome"]

- name: make sure the gdm directory exists
  file:
    path: /etc/dconf/db/gdm.d
    state: directory
  tags: ["gnome"]

- name: create gdm keyfile for machine-wide settings
  copy:
    content: |
      [org/gnome/login-screen]
      # Do not show the user list
      disable-user-list=true
    dest: /etc/dconf/db/gdm.d/00-login-screen
  tags: ["gnome"]

- name: update the system databases
  command: dconf update
  tags: ["gnome"]

- name: update gnome-terminal theme
  become: "{{ ansible_user_id }}"
  get_url:
    url: "https://raw.githubusercontent.com/arcticicestudio/nord-gnome-terminal/develop/src/nord.sh"
    dest: "{{ ansible_user_dir }}/Downloads/nord.sh"
  tags: ["gnome"]

- name: install wayland
  yum:
    name: gnome-session-wayland-session
    state: present
  tags: ["gnome"]
